### ISSUE TITLE
TS 2740 implementation

### ISSUE THREAD

**Issue by princejoogie** [davidosomething/format-ts-errors.nvim#1]
![image](https://user-images.githubusercontent.com/47204120/235351822-ca6ec40a-fe61-4c0b-b03c-0aba36b9ef99.png)

**Comment by davidosomething** [comment]
almost identical to 2739... https://github.com/Microsoft/TypeScript/blob/v5.1-beta/src/compiler/diagnosticMessages.json#L3238-L3245

can you try the `ts2740` branch?
add `branch = "ts2740"` if using lazy plugin manager

**Comment by davidosomething** [comment]
did it work @princejoogie ?

**Comment by princejoogie** [comment]
hey @davidosomething had lots of errands. got to check it right now and it seems to work! thankss!
![image](https://user-images.githubusercontent.com/47204120/235938324-0bacfd1f-b16d-4ae7-b334-914c5a2feb09.png)
