### ISSUE TITLE
Show full formatted error message

### ISSUE THREAD

**Issue by aonemd** [davidosomething/format-ts-errors.nvim#3]
Hello, thanks a lot for making this plugin! 

I noticed that if the formatted error message is too long (longer than the length of the hover window), the hover window doesn't show the full text; shows only a cut-off message. Is there a way to get the full message or to scroll through the error messages?

**Comment by Picalines** [comment]
Hi, @aonemd! In the latest neovim you can press `<C-w>d` to show the error in a popup window, and then `<C-w>d` again to focus it

Then you close the popup by `q` or `<C-w>c`. Regular lsp hover (usually captial `K`) also works that way, so you can read a long docstring

**Comment by davidosomething** [comment]
also check your tsconfig settings
https://www.typescriptlang.org/tsconfig/#noErrorTruncation

**Comment by davidosomething** [comment]
closed, not in this plugin's scope
