### ISSUE TITLE
TS 7053 implementation

### ISSUE THREAD

**Issue by lmquansgt** [davidosomething/format-ts-errors.nvim#4]
Hello. I recently switched to using this instead of lspsaga and it have been great.
I would like to know if 7053 formatting have been added yet or there's something wrong with my config. I tested and saw 2345's properly formatted.
Thank you very much.
![image](https://github.com/davidosomething/format-ts-errors.nvim/assets/130047938/9e6955a9-fb11-47eb-80c9-fd4a1bc4c66d)

**Comment by davidosomething** [comment]
Do you have a file or github gist I can test/replicate this on?

**Comment by lmquansgt** [comment]
https://gist.github.com/lmquansgt/2af8896b395544d4392ae99457a07c33
Is this okay?
![image](https://github.com/davidosomething/format-ts-errors.nvim/assets/130047938/34f3859b-496a-4f11-ae72-8885fd1a37ab)

**Comment by davidosomething** [comment]
maybe need your tsconfig too

**Comment by lmquansgt** [comment]
I managed to trigger the error in new folder with this tsconfig.json and latest typescript.
```
{
  "compilerOptions": {
    "strict": true
  }
}
```

**Comment by davidosomething** [comment]
updated plugin, 
i recommend adding    "noErrorTruncation": true
to compiler options too

**Comment by lmquansgt** [comment]
It look great. TYVM!
